name: kitchen_organizer_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-151.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.7.1 # This is the correct package for Cloud Functions
  dropdown_search: ^5.0.6
  fl_chart: ^0.68.0
  # State Management
  flutter_riverpod: ^2.5.1

  # Utility & Network Packages
  file_picker: ^8.0.6
  csv: ^6.0.0
  intl: ^0.20.2
  http: ^1.2.1
  rxdart: ^0.27.7
  async: ^2.11.0 # Added this missing dependency


  # Icons
  cupertino_icons: ^1.0.6
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Asset declaration for your custom fonts
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: DistinctStyleSans # This is the name you'll use in your TextStyle
      fonts:
        - asset: assets/fonts/distinct-style-sans.ttf