// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzdUWU8lgNT7mIbAVfAHd9c8elAilfZr4',
    appId: '1:230443187002:web:e9ad540e7ac9906d71ae03',
    messagingSenderId: '230443187002',
    projectId: 'unmercato1',
    authDomain: 'unmercato1.firebaseapp.com',
    storageBucket: 'unmercato1.firebasestorage.app',
    measurementId: 'G-ESP15KG6JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChdNfLkRMrkDFeDYKBTajp3x4lAJcvW5s',
    appId: '1:230443187002:android:59630676438381d771ae03',
    messagingSenderId: '230443187002',
    projectId: 'unmercato1',
    storageBucket: 'unmercato1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxDf84xGgIEE9ULDxl9w9juOT3oSbjsUI',
    appId: '1:230443187002:ios:352ce130a5e9826571ae03',
    messagingSenderId: '230443187002',
    projectId: 'unmercato1',
    storageBucket: 'unmercato1.firebasestorage.app',
    iosBundleId: 'com.example.kitchenOrganizerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxDf84xGgIEE9ULDxl9w9juOT3oSbjsUI',
    appId: '1:230443187002:ios:352ce130a5e9826571ae03',
    messagingSenderId: '230443187002',
    projectId: 'unmercato1',
    storageBucket: 'unmercato1.firebasestorage.app',
    iosBundleId: 'com.example.kitchenOrganizerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzdUWU8lgNT7mIbAVfAHd9c8elAilfZr4',
    appId: '1:230443187002:web:7425ad6a2f5f039471ae03',
    messagingSenderId: '230443187002',
    projectId: 'unmercato1',
    authDomain: 'unmercato1.firebaseapp.com',
    storageBucket: 'unmercato1.firebasestorage.app',
    measurementId: 'G-RJV08CE04S',
  );
}
